#!/bin/bash

if [ $# -eq 1 ]
then
    git add "$1"
    git commit -m "[fix] coding style"
    git push
elif [ $# -gt 1 ]
then
    for ((i = 1; i <= $#; ++i))
    do
        git add "${!i}"
    done
    git commit -m "[fix] coding style"
    git push
else
    git add .
    git commit -m "[fix] coding style"
    git push
fi
