#!/bin/bash

function git_add_arg()
{
    for ((i = 1; i <= $#; ++i))
    do
        git add "${!i}"
    done
    return 0
}

function git_commit()
{
    read -p 'Commit message: ' commit_message
    if ((${#commit_message} == 0))
    then
        git commit -m "[fix] coding style"
    else
        git commit -m "$commit_message"
    fi
}

function git_add_all()
{
    end=0
    while((end == 0))
    do
        echo "Are you sure you want push everything ? (y/n)"
        read answer
        if ((${#answer} == 0)) || [ "$answer" = "y" ]
        then
            git add .
            git_commit
            git push
            end=1
        elif [ "$answer" = "n" ]
        then
            end=1
        fi
    done
}

function push()
{
    if [ $# -gt 0 ]
    then
        git_add_arg "$@"
        git_commit
        git push
    else
        git_add_all
    fi
}

push "$@"
