#!/bin/bash

echo "${!#}"
if [ $# -eq 1 ]
then
    git add .
    git commit -m "$1"
    git push
elif [ $# -gt 1 ]
then
    for ((i = 1; i <= $#; ++i))
    do
        git add "$i"
    done
    git commit -m "${!#}"
    git push
else
    git add .
    git commit -m "[add]"
    git push
fi
