#!/bin/bash

echo "${!#}"
if [ $# -gt 1 ]
then
    git add .
    git commit -m "$1"
    git push
elif [ $# -gt 1 ]
then
    for ((i = 1; i < $#; ++i))
    do
        echo "$i"
    done
    #git commit -m "${!#}"
    #git push
else
    echo "ahha"
    git add .
    git commit -m "[add]"
    git push
fi
